<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://mycompany.com/etudiant"
           xmlns="http://mycompany.com/etudiant"
           elementFormDefault="qualified">

    <xs:element name="etudiant" type="EtudiantType"/>

    <xs:complexType name="EtudiantType">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
            <xs:element name="filiere" type="xs:string"/>
            <xs:element name="annee" type="xs:int"/>
            <xs:element name="notes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="note" type="xs:double" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>

</xs:schema>
